CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" varchar NOT NULL,
  "description" text NOT NULL,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" varchar NOT NULL,
  "url" text NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "video_user" (
  "users_id" int,
  "course_videos_id" int
);

CREATE TABLE "categories_courses" (
  "categories_id" int,
  "courses_id" int
);

CREATE TABLE "categories_users" (
  "users_id" int,
  "categories_id" int
);

CREATE TABLE "users_courses" (
  "users_id" int,
  "courses_id" int
);

CREATE TABLE "videos_courses" (
  "courses_id" int,
  "course_videos_id" int
);

ALTER TABLE "video_user" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "video_user" ADD FOREIGN KEY ("course_videos_id") REFERENCES "course_videos" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "categories_users" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "categories_users" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("course_videos_id") REFERENCES "course_videos" ("id");

insert into users (
	name,
	email,
	"password" ,
	age
) values (
	'Pierina',
	'pierina@gmail.com',
	'111222',
	'25'
);

insert into users (
	name,
	email,
	"password" ,
	age
) values (
	'eloy',
	'sandoval@gmail.com',
	'555222',
	'30'
);

insert into users (
	name,
	email,
	"password" ,
	age
) values (
	'edgar',
	'edgar@gmail.com',
	'55552',
	'30'
) , (
	'misael',
	'misa@gmail.com',
	'48798',
	'25'
);



insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'react',
	'curso de front',
	'avanzado',
	'junior'
);

insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'html',
	'curso de programacion',
	'principiante',
	'jesus'
);

insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'javaScript',
	'lenguaje de programacion',
	'avanzado',
	'abraham'
);

insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'nodeJs',
	'curso de backend',
	'avanzado',
	'sahid'
);

insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'css',
	'curso de front',
	'intermedio',
	'jesus'
);

insert into courses (
	title_id,
	description,
	level,
	teacher 
) values (
	'angular',
	'curso de front',
	'avanzado',
	'sahid'
);


insert into course_videos (
	title_id,
	url
) values (
	'maquetado con tailwind',
	'dbdiagram.io/d/64154f28296d97641d88e693'
);

insert into course_videos (
	title_id,
	url
) values (
	'redux',
	'dbdiagram.io/d/64154f28296d97641d88e693'
);

insert into course_videos (
	title_id,
	url
) values (
	'maquetado con html',
	'dbdiagram.io/d/64154f28296d97641d88e693'
);

insert into course_videos (
	title_id,
	url
) values (
	'ejercicios de logica',
	'dbdiagram.io/d/64154f28296d97641d88e693'
);

insert into course_videos (
	title_id,
	url
) values (
	'tablas',
	'dbdiagram.io/d/64154f28296d97641d88e693'
);

insert into categories (
	name
) values (
	'All'
);

insert into categories (
	name
) values (
	'TI'
);

insert into categories (
	name
) values (
	'frontend'
);

insert into categories (
	name
) values (
	'backend'
);




