CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" varchar NOT NULL,
  "description" text NOT NULL,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" varchar NOT NULL,
  "url" text NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "video_user" (
  "users_id" int,
  "course_videos_id" int
);

CREATE TABLE "categories_courses" (
  "categories_id" int,
  "courses_id" int
);

CREATE TABLE "categories_users" (
  "users_id" int,
  "categories_id" int
);

CREATE TABLE "users_courses" (
  "users_id" int,
  "courses_id" int
);

CREATE TABLE "videos_courses" (
  "courses_id" int,
  "course_videos_id" int
);

ALTER TABLE "video_user" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "video_user" ADD FOREIGN KEY ("course_videos_id") REFERENCES "course_videos" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "categories_users" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "categories_users" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("course_videos_id") REFERENCES "course_videos" ("id");
